package com.momoyeyu.smali_analyzer.element.instructions;

public enum INSTRUCTION_TYPE {
    DEFAULT,
    CATCH, CATCHALL,
    CONDITION,
    CONST, CONST_STRING, CONST_CLASS,
    EXCEPTION,
    GOTO,
    INVOKE, INVOKE_STATIC, INVOKE_DIRECT, INVOKE_VIRTUAL, INVOKE_SUPER, INVOKE_INTERFACE, INVOKE_CONSTRUCTOR,
    LABEL, LABEL_CONDITION, LABEL_GOTO, LABEL_TRY_START, LABEL_TRY_END,
    MOV, MOV_ARRAY,
    NEW, NEW_INSTANCE, NEW_ARRAY,
    RESULT,
    RETURN, RETURN_VOID,
    SYNCHRONIZED,
    TAG, TAG_END_METHOD,
    THROW;
}