package com.momoyeyu.smali_analyzer.element.instructions;

public enum INSTRUCTION_TYPE {
    DEFAULT,
    INVOKE, INVOKE_STATIC, INVOKE_DIRECT, INVOKE_VIRTUAL, INVOKE_SUPER, INVOKE_INTERFACE,
    CONST, CONST_STRING, CONST_CLASS,
    MOV, MOV_ARRAY,
    NEW, NEW_INSTANCE, NEW_ARRAY,
    RESULT,
    RETURN, RETURN_VOID
}